### ISSUE TITLE
typeSolver is null when trying to resolve ArrayList.size() function.

### ISSUE THREAD

**Issue by emanguy** [ftomassetti/java-symbol-solver#15]
While trying to solve for a MethodCallExpr, ```ArrayList<Tire>.size()```, I encounter a problem where the type solver becomes "null" when attempting to solve the local class "Tire".

Here is the code directory I'm testing:
TestData
|
|-- Car.java
|
|-- Tire.java

The code for both Car and Tire are in the output of running my program. The program creates a CombinedTypeSolver from both a JavaParserTypeSolver and the JreTypeSolver. It then uses a MethodDeclarationVisitor to visit the methods declared in Car.java. See output below:

```
java -cp "lib/javaparser/javaparser-core/target/javaparser-core-2.3.1-SNAPSHOT.jar:lib/java-symbol-solver/java-symbol-solver-core/build/libs/java-symbol-solver-core-0.2.0-SNAPSHOT.jar:lib/java-symbol-solver/java-symbol-solver-logic/build/libs/java-symbol-solver-logic-0.2.0-SNAPSHOT.jar:lib/java-symbol-solver/java-symbol-solver-model/build/libs/java-symbol-solver-model-0.2.0-SNAPSHOT.jar":build/ Test TestData/Car.java TestData/
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
----------------------------------------
Got base code directory as TestData/.
PARSING TESTDATA/CAR.JAVA:

import java.util.ArrayList;

public class Car {

    private int year;

    private String manufacturer;

    private ArrayList<Tire> tires;

    public  Car(String manufacturer, int year) {
        this.manufacturer = new String(manufacturer);
        this.year = year;
        this.tires = new ArrayList<Tire>();
        for (int tire = 0; tire < 4; tire++) {
            tires.add(new Tire());
        }
    }

    public int getYear() {
        return year;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public double getAverageTirePressure() {
        double totalTires = tires.size();
        double totalPressure = 0;
        for (Tire t : tires) {
            totalPressure += t.getPressure();
        }
        return totalPressure / totalTires;
    }
}

Type solve Tire: SymbolReference{correspondingDeclaration=Optional[JavaParserClassDeclaration{wrappedNode=public class Tire {

    private int pressure;

    private double health;

    public  Tire() {
        pressure = 100;
        health = 1.0;
    }

    public  Tire(int pressure, double health) {
        this.pressure = pressure;
        this.health = health;
    }

    public int getPressure() {
        return pressure;
    }

    public double getHealth() {
        return health;
    }
}}]}
Found method call: tires.size() called from object tires
Exception in thread "main" UnsolvedSymbolException{context='unknown', name='Tire', typeSolver=null}
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:438)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:428)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.lambda$convertToUsage$13(JavaParserFacade.java:443)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade$$Lambda$4/1618212626.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:443)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:428)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:481)
	at me.tomassetti.symbolsolver.javaparsermodel.declarations.JavaParserSymbolDeclaration.getType(JavaParserSymbolDeclaration.java:131)
	at me.tomassetti.symbolsolver.model.resolution.Value.from(Value.java:22)
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveWithAsValue(AbstractJavaParserContext.java:72)
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbolAsValue(ClassOrInterfaceDeclarationContext.java:77)
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodContext.solveSymbolAsValue(MethodContext.java:61)
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:57)
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:88)
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:197)
	at me.tomassetti.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:42)
	at me.tomassetti.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:47)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:211)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:136)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:130)
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:203)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:122)
	at Test$FunctionCallVisitor.visit(Test.java:99)
	at Test$FunctionCallVisitor.visit(Test.java:88)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:73)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:782)
	at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:69)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:774)
	at com.github.javaparser.ast.expr.VariableDeclarationExpr.accept(VariableDeclarationExpr.java:77)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:407)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:53)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:169)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:567)
	at Test$FunctionDeclarationVisitor.visit(Test.java:84)
	at Test$FunctionDeclarationVisitor.visit(Test.java:73)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:113)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:231)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:85)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:260)
	at Test.main(Test.java:46)
```

**Comment by ftomassetti** [comment]
I wonder if this is due to the fact that they are in the default package. You cannot import stuff from the default package so it is treated differently. You should be able to refer to stuff in the default package from other classes in it. I will have a look. Thank you for reporting this!

**Comment by emanguy** [comment]
I'll assign the test code to a package and re-run the symbol solver.

**Comment by emanguy** [comment]
Update: I assigned the package "edu.evan.test" to both files and reorganized the directory hierarchy to fit the package. That solved the issue.

**Comment by emanguy** [comment]
Adding onto this-- apparently trying to use ```MethodCallExpr.getName()``` or ```JavaParserFacade.solve()``` on a MethodCallExpr which contains ```System.out.println()``` throws a NoClassDefFoundError.

**Comment by ftomassetti** [comment]
I am using gradle to manage the dependencies and here (https://github.com/ftomassetti/java-symbol-solver/blob/master/java-symbol-solver-core/build.gradle) I read guava 0.18.0. Are you using gradle, maven or just copying dependencies manually?

**Comment by emanguy** [comment]
I'm doing everything from the command line so I used the gradlew executable you included to install the new version of the project. I looked at the output from the gradle build and thought it indirectly grabbed guava through maven. Even if I include guava-core-18.0-SNAPSHOT.jar from my ~/.m2 directory it still thinks that class isn't defined. I'll figure it out.

**Comment by emanguy** [comment]
If the "jar" build method doesn't grab dependencies I can look into the other build options to see if I can fetch them

**Comment by emanguy** [comment]
Using ./gradlew buildNeeded pulled the dependencies and I was using the wrong command before.
