### ISSUE TITLE
UnsupportedOperationException when solving MethodCallExpr on super

### ISSUE THREAD

**Issue by mlangkabel** [ftomassetti/java-symbol-solver#41]
I just wanted to report this exception: 

In my code I have an ASTVisitor that overrides the `public void visit(final MethodCallExpr n, final Void v)`. Inside this method I'm calling `JavaParserFacade.get(typeSolver).solveMethodAsUsage(n);` 
When running the ASTVisitor on the following code
```
public class Bla {
	public class Superclass {
		public void foo() {
		}
	}

	public class Subclass extends Superclass {
		public void foo() {
			super.foo();
		}
	}
}
```
this call results in an UnsupportedOperationException. Here's the callstack:
```
Exception in thread "Thread-3" java.lang.UnsupportedOperationException: com.github.javaparser.ast.expr.SuperExpr
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:394)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:136)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:130)
        at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:156)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:496)
        at io.coati.JavaAstVisitor.visit(JavaAstVisitor.java:371)
        at io.coati.JavaAstVisitor.visit(JavaAstVisitor.java:1)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:73)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:399)
        at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:53)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
        at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:58)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:562)
        at io.coati.JavaAstVisitor.visit(JavaAstVisitor.java:216)
        at io.coati.JavaAstVisitor.visit(JavaAstVisitor.java:1)
        at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:111)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:223)
        at io.coati.JavaAstVisitor.visit(JavaAstVisitor.java:135)
        at io.coati.JavaAstVisitor.visit(JavaAstVisitor.java:1)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:85)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:223)
        at io.coati.JavaAstVisitor.visit(JavaAstVisitor.java:135)
        at io.coati.JavaAstVisitor.visit(JavaAstVisitor.java:1)
        at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:85)
        at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:251)
        at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:84)
        at io.coati.JavaIndexer.processFile(JavaIndexer.java:107)
```

However, solving a call to `this.foo()` works fine.

**Comment by mlangkabel** [comment]
Fixed with merge of pull request #55
